// Generated by GraalHax - GS2 Bytecode Injector for Graal Worlds
// Test script - replace "00 01 02" with your actual bytecode hex

function create_tstring(e) {
    const r = Memory.alloc(8);
    const a = Memory.alloc(e.length + 8 + 10);
    r.writePointer(a);
    a.writeInt(e.length);
    ptr(parseInt(a) + 4).writeInt(100);

    for (let i = 0; i < e.length; i++) {
        ptr(parseInt(a) + 8).add(i).writeU8(e.charCodeAt(i));
    }
    ptr(parseInt(a) + 8).add(e.length).writeU8(0);
    return r;
}

const hexToBytecode = (hex) => {
    return hex.split(" ").map(byte => String.fromCharCode(parseInt(byte, 16))).join("");
};

async function injectBytecode(variableName, bytecodeHex) {
    var baseAddress = Process.findModuleByName("Worlds.exe").base;

    const TGraalVar_TGraalVar = new NativeFunction(
        baseAddress.add(0x9A340), 'void', ['pointer', 'pointer']);
    const TGraalVar_SetScript = new NativeFunction(
        baseAddress.add(0x9EDE0), 'void', ['pointer', 'pointer']);

    console.log("Allocating variable memory...");
    const variable = Memory.alloc(0x1000);

    console.log("Creating TGraalVar with name: " + variableName);
    TGraalVar_TGraalVar(variable, create_tstring(variableName));

    console.log("Setting script bytecode (" + bytecodeHex.length / 3 + " bytes)...");
    TGraalVar_SetScript(variable, create_tstring(hexToBytecode(bytecodeHex)));

    console.log("SCRIPT INJECTED successfully");
    return true;
}

// Auto-inject on script load
injectBytecode('.', "00 01 02").catch(err => {
    console.log("Injection error: " + err);
});
