// Generated by GraalHax - GS2 Bytecode Injector for Graal Worlds
// Test script - replace "00 01 02" with your actual bytecode hex

function create_tstring(str) {
    const strLen = str.length;
    const totalSize = 8 + strLen + 1; // length(4) + value(4) + data + null

    const strPtr = Memory.alloc(totalSize);
    strPtr.writeU32(strLen);           // [0-3]: length
    strPtr.add(4).writeU32(100);       // [4-7]: value/flags

    // Write string data starting at offset 8
    const dataPtr = strPtr.add(8);
    for (let i = 0; i < strLen; i++) {
        dataPtr.add(i).writeU8(str.charCodeAt(i));
    }
    dataPtr.add(strLen).writeU8(0);    // null terminator

    // Return a pointer to the structure
    const refPtr = Memory.alloc(8);
    refPtr.writePointer(strPtr);
    return refPtr;
}

const hexToBytes = (hex) => {
    return hex.split(" ").map(byte => parseInt(byte, 16));
};

async function injectBytecode(variableName, bytecodeHex) {
    var baseAddress = Process.findModuleByName("Worlds.exe").base;

    const TGraalVar_TGraalVar = new NativeFunction(
        baseAddress.add(0x9A340), 'void', ['pointer', 'pointer']);
    const TGraalVar_SetScript = new NativeFunction(
        baseAddress.add(0x9EDE0), 'void', ['pointer', 'pointer']);

    console.log("Allocating variable memory...");
    const variable = Memory.alloc(0x1000);

    console.log("Creating TGraalVar with name: " + variableName);
    TGraalVar_TGraalVar(variable, create_tstring(variableName));

    console.log("Setting script bytecode (" + bytecodeHex.length / 3 + " bytes)...");
    const bytes = hexToBytes(bytecodeHex);
    const bytecodeStructSize = 8 + bytes.length + 1;
    const bytecodeStruct = Memory.alloc(bytecodeStructSize);
    bytecodeStruct.writeU32(bytes.length);
    bytecodeStruct.add(4).writeU32(100);

    const bytecodeData = bytecodeStruct.add(8);
    for (let i = 0; i < bytes.length; i++) {
        bytecodeData.add(i).writeU8(bytes[i]);
    }
    bytecodeData.add(bytes.length).writeU8(0);

    const bytecodeRef = Memory.alloc(8);
    bytecodeRef.writePointer(bytecodeStruct);

    TGraalVar_SetScript(variable, bytecodeRef);

    console.log("SCRIPT INJECTED successfully");
    return true;
}

// Auto-inject on script load
injectBytecode('.', "00 01 02").catch(err => {
    console.log("Injection error: " + err);
});
